# Generated by Django 4.0.4 on 2022-04-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.IntegerField(max_length=6)),
                ('doc_number', models.IntegerField(max_length=10)),
                ('doc_date', models.DateTimeField()),
                ('employee_code', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department_code', models.IntegerField(max_length=6)),
                ('room', models.IntegerField(max_length=3)),
                ('position_code', models.IntegerField(max_length=3)),
                ('phone', models.IntegerField(blank=True, max_length=11)),
                ('home_address', models.CharField(blank=True, max_length=150)),
                ('fixing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('inv_number', models.IntegerField(max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.IntegerField(max_length=6)),
                ('nomenclature_code', models.IntegerField(max_length=6)),
            ],
        ),
    ]
