# Generated by Django 4.0.4 on 2022-04-28 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docs',
        ),
        migrations.DeleteModel(
            name='Registry',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='position_code',
        ),
        migrations.AddField(
            model_name='employees',
            name='nomenclature_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='invertory.nomenclature'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='room',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='inv_number',
            field=models.IntegerField(),
        ),
    ]
