# Generated by Django 4.0.4 on 2022-04-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0002_delete_docs_delete_registry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='department_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='invertory.departments'),
        ),
        migrations.AddField(
            model_name='employees',
            name='position_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='invertory.positions'),
        ),
    ]
