# Generated by Django 4.0.4 on 2022-04-28 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0003_departments_positions_employees_department_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.IntegerField()),
                ('doc_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Docs_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='invertory.docs')),
                ('nomenclature_code', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='invertory.nomenclature')),
            ],
        ),
        migrations.AddField(
            model_name='docs',
            name='doc_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='invertory.docs_type'),
        ),
        migrations.AddField(
            model_name='docs',
            name='employee_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='invertory.employees'),
        ),
    ]
