# Generated by Django 4.0.4 on 2022-04-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0004_docs_docs_type_registry_docs_doc_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='doc_type',
            new_name='doc',
        ),
        migrations.RenameField(
            model_name='docs',
            old_name='employee_code',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='department_code',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='nomenclature_code',
            new_name='nomenclature',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='position_code',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='registry',
            old_name='document_code',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='registry',
            old_name='nomenclature_code',
            new_name='nomenclature',
        ),
    ]
