# Generated by Django 4.0.4 on 2022-04-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0005_rename_doc_type_docs_doc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positions',
            old_name='position',
            new_name='title',
        ),
    ]
