# Generated by Django 4.0.4 on 2022-04-30 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0006_rename_position_positions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='place',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='status',
            field=models.CharField(choices=[('GOOD', 'исправен'), ('BAD', 'неисправен'), ('REP', 'в ремонте')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Amortization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lifetime', models.IntegerField()),
                ('nomenclature', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='invertory.nomenclature')),
            ],
        ),
    ]
