# Generated by Django 4.0.4 on 2022-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0007_nomenclature_place_nomenclature_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='doc_number',
        ),
        migrations.AlterField(
            model_name='docs',
            name='doc_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
