# Generated by Django 4.0.4 on 2022-04-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0008_remove_docs_doc_number_alter_docs_doc_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='fixing_date',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='inv_number',
        ),
        migrations.AddField(
            model_name='registry',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='invertory.employees'),
        ),
    ]
