# Generated by Django 4.0.4 on 2022-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0009_remove_docs_employee_remove_employees_fixing_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='nomenclature',
        ),
        migrations.AlterField(
            model_name='employees',
            name='home_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='room',
            field=models.IntegerField(blank=True),
        ),
    ]
