# Generated by Django 4.0.4 on 2022-04-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0011_statuses_alter_nomenclature_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='invertory.docs_type'),
        ),
        migrations.DeleteModel(
            name='Docs',
        ),
    ]
