# Generated by Django 4.0.4 on 2022-05-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0014_alter_registry_nomenclature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortization',
            name='nomenclature',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='invertory.nomenclature'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invertory.departments'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invertory.positions'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invertory.statuses'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invertory.docs_type'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invertory.employees'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='nomenclature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invertory.nomenclature'),
        ),
    ]
