# Generated by Django 4.0.4 on 2022-05-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0016_places_alter_nomenclature_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docs_type',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invertory.positions'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
