# Generated by Django 4.0.4 on 2022-05-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invertory', '0017_alter_departments_title_alter_docs_type_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='docs_type',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invertory.positions'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='statuses',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
